FROM nginx:alpine

# Копируем наш index.html в стандартную директорию nginx
COPY index.html /usr/share/nginx/html/index.html

# Порт 80 открыт по умолчанию в nginx image, но явно укажем его для документации
EXPOSE 80
